#!/bin/bash
#################
## Author: SIRIO MAQUEA ALVES
## GitHub: @siriomaquea
## Linkedin: https://www.linkedin.com/in/siriomaqueaalves/
#################
##change to your hd name
HDNAME="HARD DISK NAME"